### PR TITLE
Remove profanities from wordlist

### PR DESCRIPTION
**Pull request by Recursing**
Nice project!

Could be a bit embarrassing if one of these words ends up as word of the day.

You might also want to remove 'cesso' and/or 'tette' and in general check with a list of "bad" words

### CODE REVIEW

**Comment by pietroppeter** [comment]
Hi yes, I need to curate the dictionary better. Unfortunately I need a way to do this programmatically in a way that keeps past words in the order as they are so I cannot merge this. I checked already that in the next few weeks there are no embarrassing words coming up and I plan to clean it up before that happens

**Comment by Recursing** [comment]
I'll close this then, good luck!

**Comment by caco3** [comment]
As a suggestion, have a look on my variant (https://github.com/caco3/wordle-de).
It stores the timestamp of the day as well as today's word in the browsers localstorage.
This way I can update the word list and who ever already played on that day will keep their word until the next day.

**Comment by Recursing** [comment]
I think replacing unwanted words instead of removing them might be an
easier fix, if it doesn't affect the final ordering

**Comment by pietroppeter** [comment]
the intent of this PR has been merged through #25

**Pull request closed without merging**
